pipeline {
    agent any
    stages {
        stage('LS') {
            steps {
                sh 'ls'
                sh 'php --version'
                sh 'node --version'
                sh 'php artisan serve --host 172.31.26.247 --port 8000'
            }
        }
    }
}
